print("3개의 과목의 시험 점수를 차례대로 입력하세요!")
korean = int(input("국어: "))
english = int(input("영어: "))
math = int(input("수학: "))

print("================")
print("= 시험 점수 결과 =")
print("================")
print(f"* 국어 점수: {korean}")
print(f"* 영어 점수: {english}")
print(f"* 수학 점수: {math}")
print("================")
print(f"* 총 합계 점수: {korean + english + math}")
print(f"* 평균 점수: {round((korean + english + math)/3, 2)}")
print("================")
